server:
  port: ${BIDDING_SERVICE_PORT:8083}

spring:
  config:
    import: optional:file:.env[.properties],optional:file:../../.env[.properties]

  application:
    name: bidding-service

  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5433}/${POSTGRES_DB:online_auction}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: bidding
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    default-schema: bidding
    schemas: bidding
    locations: classpath:db/migration

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.flywaydb: INFO