server:
  port: ${AUTH_SERVICE_PORT:8081}

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5433}/${POSTGRES_DB:online_auction}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: auth
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
    default-schema: auth
    schemas: auth
    locations: classpath:db/migration

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.flywaydb: INFO